1.0.0:
  static:
    windows-x64: https://example.com/package/1_0_0-static-win64.tar.gz
    windows-x32: https://example.com/package/1_0_0-static-win32.tar.gz
  dynamic:
    windows-x64: https://example.com/package/1_0_0-dynamic-win64.tar.gz
  source: https://example.com/package/1_0_0-source.tar.gz
  dependencies:
    - package-a:
        version: 1.0.0
        distribution: static
    - package-b:
        version: 1.0.0
        distribution: dynamic
